### ISSUE TITLE
Feature: List of stores that have items currently listed

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/Bangazon-API-Spicy-Boys-V2#36]
**Given** a user is authenticated
**When** the **Stores** nav item is clicked
**Then** the user should see a list of stores that have items for sale

The list view should show the store name, the store description, the name of the store's seller, and a count of how many items are currently for sale. Underneath that information, a list of products should be displayed. These should be rendered just as they are on the main product list view.

**Comment by BlakeJonMycal** [comment]
@stevebrownlee  Should products of a store be displayed on the all-stores view, as described in the ticket, or should products be displayed in the store details view, as seen on the gif provided?
