### ISSUE TITLE
Bug: All products not displaying after user is authenticated

### ISSUE THREAD

**Issue by BlakeJonMycal** [day-cohort-70/Bangazon-API-Spicy-Boys-V2#37]
When a user logs in all products should be displayed.

Also, check routing issue upon log-in. Should user be directed too 3000/products at log in?

currently receiving 500 internal server error

**Comment by DannyJamesHidalgo** [comment]
![Image](https://github.com/day-cohort-70/Bangazon-API-Spicy-Boys-V2/assets/153870143/ff6984d2-b772-490b-9e21-0334f36b5aeb)
